FROM node:26.5.0-slim AS builder

WORKDIR /shared
COPY shared/package.json shared/package-lock.json ./
RUN npm ci
COPY shared/tsconfig.json ./
COPY shared/src/ ./src/

WORKDIR /app
COPY backend/package.json backend/package-lock.json ./
RUN npm ci
COPY backend/tsconfig.json ./
COPY backend/src/ ./src/
RUN npx tsc --build

FROM node:26.5.0-slim

WORKDIR /shared
COPY shared/package.json shared/package-lock.json ./
RUN npm ci --omit=dev
COPY --from=builder /shared/dist ./dist

WORKDIR /app
COPY backend/package.json backend/package-lock.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["node", "dist/server.js"]
